# Generated by Django 3.2.4 on 2021-06-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='cursoadd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
